name: sway
description: My image for sway based on ublue

base-image: ghcr.io/ublue-os/sericea-main
image-version: 40

modules:
  - type: files
    files:
      - source: system
        destination: /

  - from-file: sddm-packages.yml
  - from-file: common-packages.yml
  - from-file: common-files.yml
  - from-file: common-scripts.yml
  - from-file: fonts.yml

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - org.mozilla.firefox

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
